export interface Deal {
  id: string;
  Product: string; // nama BDM/Product Specialist
  Enduser: string; // nama perusahaan end user/klien akhir
  Partner: string; // nama partner/reseller
  AM_Cisco: string; // nama Account Manager Cisco yang handle
  Pricelist: number; // harga list sebelum diskon
  Disc: number; // persentase diskon (misal: 42 untuk 42%)
  Value_Net: number; // nilai bersih setelah diskon
  Archi: string; // kategori arsitektur (EN, DC, SEC, COLLAB, dll)
  DID: string; // Deal ID unik
  Estimate: string; // kode estimasi internal
  Stage: number; // probabilitas closing dalam % (0, 10, 25, 50, 75, 90, 100)
  Req_Masuk_Date?: string; // (YYYY-MM-DD)
  Req_Masuk: string; // fiscal quarter request masuk (misal: FY27Q1)
  Estimate_Close_Date?: string; // (YYYY-MM-DD)
  Estimate_Close: string; // estimasi fiscal quarter close (misal: FY27Q3)
  Channel_ECS: string; // nama channel ECS yang terlibat
  PIC_Presales: string; // nama presales engineer
  Remarks: string; // catatan tambahan
  ownerId?: string; // UID milik pembuat deal
  ownerEmail?: string; // Email milik pembuat deal
  updatedAt?: string; // Tanggal update terakhir
}

export const stageColors: Record<number, string> = {
  0: 'bg-gray-200 text-gray-700 border-gray-300',
  10: 'bg-red-100 text-red-700 border-red-200',
  25: 'bg-orange-100 text-orange-700 border-orange-200',
  50: 'bg-yellow-100 text-yellow-700 border-yellow-200',
  75: 'bg-blue-100 text-blue-700 border-blue-200',
  90: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  100: 'bg-green-600 text-white border-green-700',
};

export const initialDeals: Deal[] = [
  {
    id: '1',
    Product: 'Rina (BDM EN)',
    Enduser: 'Kawan Lama',
    Partner: 'Berca',
    AM_Cisco: 'Puji',
    Pricelist: 100000,
    Disc: 42,
    Value_Net: 58000,
    Archi: 'EN',
    DID: 'DID-1001',
    Estimate: 'EST-9300-KL',
    Stage: 50,
    Req_Masuk_Date: '2026-08-15',
    Req_Masuk: 'FY27Q1',
    Estimate_Close_Date: '2027-02-15',
    Estimate_Close: 'FY27Q3',
    Channel_ECS: 'TechData',
    PIC_Presales: 'Bima',
    Remarks: 'Waiting for POC result',
  },
  {
    id: '2',
    Product: 'Andi (BDM DC)',
    Enduser: 'Pertamina',
    Partner: 'Mitra',
    AM_Cisco: 'Budi',
    Pricelist: 250000,
    Disc: 50,
    Value_Net: 125000,
    Archi: 'DC',
    DID: 'DID-1002',
    Estimate: 'EST-N9K-PRT',
    Stage: 75,
    Req_Masuk_Date: '2026-05-15',
    Req_Masuk: 'FY26Q4',
    Estimate_Close_Date: '2026-08-15',
    Estimate_Close: 'FY27Q1',
    Channel_ECS: 'Comstor',
    PIC_Presales: 'Cakra',
    Remarks: 'Final negotiation on terms',
  },
  {
    id: '3',
    Product: 'Siska (BDM SEC)',
    Enduser: 'Alfamart',
    Partner: 'Lintasarta',
    AM_Cisco: 'Rian',
    Pricelist: 80000,
    Disc: 40,
    Value_Net: 48000,
    Archi: 'SEC',
    DID: 'DID-1003',
    Estimate: 'EST-FP-ALF',
    Stage: 25,
    Req_Masuk_Date: '2026-08-10',
    Req_Masuk: 'FY27Q1',
    Estimate_Close_Date: '2026-11-15',
    Estimate_Close: 'FY27Q2',
    Channel_ECS: 'Ingram',
    PIC_Presales: 'Deni',
    Remarks: 'Initial proposal sent',
  },
  {
    id: '4',
    Product: 'Doni (BDM Collab)',
    Enduser: 'BRI',
    Partner: 'Berca',
    AM_Cisco: 'Sari',
    Pricelist: 50000,
    Disc: 30,
    Value_Net: 35000,
    Archi: 'COLLAB',
    DID: 'DID-1004',
    Estimate: 'EST-WBX-BRI',
    Stage: 100,
    Req_Masuk_Date: '2026-06-15',
    Req_Masuk: 'FY26Q4',
    Estimate_Close_Date: '2026-07-20',
    Estimate_Close: 'FY26Q4',
    Channel_ECS: 'TechData',
    PIC_Presales: 'Eka',
    Remarks: 'Closed - Pending Delivery',
  },
  {
    id: '5',
    Product: 'Rina (BDM EN)',
    Enduser: 'Telkom',
    Partner: 'Mitra',
    AM_Cisco: 'Puji',
    Pricelist: 120000,
    Disc: 45,
    Value_Net: 66000,
    Archi: 'EN',
    DID: 'DID-1005',
    Estimate: 'EST-MR-TLK',
    Stage: 90,
    Req_Masuk_Date: '2026-08-01',
    Req_Masuk: 'FY27Q1',
    Estimate_Close_Date: '2026-10-15',
    Estimate_Close: 'FY27Q1',
    Channel_ECS: 'Comstor',
    PIC_Presales: 'Bima',
    Remarks: 'Verbal agreement, waiting PO',
  },
  {
    id: '6',
    Product: 'Siska (BDM SEC)',
    Enduser: 'Kawan Lama',
    Partner: 'Lintasarta',
    AM_Cisco: 'Budi',
    Pricelist: 60000,
    Disc: 35,
    Value_Net: 39000,
    Archi: 'SEC',
    DID: 'DID-1006',
    Estimate: 'EST-ISE-KL',
    Stage: 10,
    Req_Masuk_Date: '2026-08-10',
    Req_Masuk: 'FY27Q1',
    Estimate_Close_Date: '2027-05-15',
    Estimate_Close: 'FY27Q4',
    Channel_ECS: 'Ingram',
    PIC_Presales: 'Deni',
    Remarks: 'First meeting next week',
  },
  {
    id: '7',
    Product: 'Andi (BDM DC)',
    Enduser: 'Pertamina',
    Partner: 'Berca',
    AM_Cisco: 'Rian',
    Pricelist: 300000,
    Disc: 55,
    Value_Net: 135000,
    Archi: 'DC',
    DID: 'DID-1007',
    Estimate: 'EST-UCS-PRT',
    Stage: 50,
    Req_Masuk_Date: '2026-06-25',
    Req_Masuk: 'FY26Q4',
    Estimate_Close_Date: '2026-11-20',
    Estimate_Close: 'FY27Q2',
    Channel_ECS: 'TechData',
    PIC_Presales: 'Cakra',
    Remarks: 'Sizing calculation ongoing',
  },
  {
    id: '8',
    Product: 'Siska (BDM SEC)',
    Enduser: 'Alfamart',
    Partner: 'Mitra',
    AM_Cisco: 'Sari',
    Pricelist: 40000,
    Disc: 20,
    Value_Net: 32000,
    Archi: 'SEC',
    DID: 'DID-1008',
    Estimate: 'EST-UMB-ALF',
    Stage: 0,
    Req_Masuk_Date: '2026-08-05',
    Req_Masuk: 'FY27Q1',
    Estimate_Close_Date: '2026-11-05',
    Estimate_Close: 'FY27Q2',
    Channel_ECS: 'Comstor',
    PIC_Presales: 'Deni',
    Remarks: 'Budget approved by management',
  }
];
